name: Bug Report
description: Create a report to help us improve
title: "bug: "
labels:
  - kind/bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug *
      description: Add logs and screenshots if any.
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproducing
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Kubernetes Version: [e.g. 1.28]
        - Toolhive Webhook Version: [e.g. v1.0.0]
    validations:
      required: false
