name: Epic
description: Create an epic to track large initiatives
title: "epic: "
labels:
  - kind/epic
body:
  - type: textarea
    id: description
    attributes:
      label: Description *
      description: A clear and concise description of the epic
      placeholder: |
        Describe the high-level goal or initiative
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: What are the main objectives of this epic?
      placeholder: |
        - Goal 1
        - Goal 2
        - Goal 3
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: User Stories
      description: List the user stories or sub-tasks that make up this epic
      placeholder: |
        - [ ] User story 1
        - [ ] User story 2
        - [ ] User story 3
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What defines completion for this epic?
      placeholder: |
        - Criteria 1
        - Criteria 2
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, dependencies, or technical considerations
    validations:
      required: false
